---
- hosts: all
  become: yes
  vars:
    java_version: java-1.8.0-openjdk
  tasks:
    - name: Install tools
      yum:
        name:
          - yum-utils
          - wget
          - git
          - python3
          - python3-pip
          - epel-release
          - curl
        state: present
        update_cache: true

    - name: Enable AppStream repository
      ansible.builtin.shell: |
        sudo dnf config-manager --set-enabled crb

    - name: Update dnf cache
      ansible.builtin.dnf:
        update_cache: yes

    - name: Install Java
      ansible.builtin.dnf:
        name: "{{ java_version }}"
        state: present
