---
- hosts: all
  become: yes
  vars:
    java_package: "{{ java_version | default('java-21-openjdk-devel') }}"
  tasks:
    - name: Install basic tools
      ansible.builtin.dnf:
        name:
          - yum-utils
          - wget
          - git
          - python3
          - python3-pip
          - epel-release
          - curl
        state: present
        update_cache: true

    - name: Enable CRB repository
      ansible.builtin.shell:
        cmd: sudo dnf config-manager --set-enabled crb
      ignore_errors: yes

    - name: Add Universal Java Repository (Adoptium)
      ansible.builtin.shell:
        cmd: |
          dnf install -y wget
          wget -O /etc/yum.repos.d/adoptium.repo https://packages.adoptium.net/artifactory/api/rpm/rhel/adoptium.repo
          rpm --import https://packages.adoptium.net/artifactory/api/gpg/key/public
          dnf update -y

    - name: Update dnf cache
      ansible.builtin.dnf:
        update_cache: yes

    - name: Debug Java package choice
      ansible.builtin.debug:
        msg: "Installing Java package: {{ java_package }}"

    - name: Check available Java packages in Adoptium repo
      ansible.builtin.shell:
        cmd: dnf search temurin | grep -i jdk || dnf search java | grep -i openjdk
      register: available_java_packages

    - name: Display available Java packages
      ansible.builtin.debug:
        var: available_java_packages.stdout_lines
